sudo: required
services:
  - docker
env:
  global:
    - IMAGE_NAME=lazzurs/jmeter

before_script:
  - version="$(awk '$2 == "JMETER_VERSION" { print $3; exit }' Dockerfile)"
script:
  - docker build --pull --tag "$IMAGE_NAME" .
  - docker run "$IMAGE_NAME" jmeter --version | grep ${version}

after_script:
  - docker images

before_deploy:
  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
  - export TAG=`if [ $TRAVIS_PULL_REQUEST == "false" ] && [ $TRAVIS_BRANCH == "master" ] ; then echo "latest"; else echo ${version}; fi`
  - docker tag "$IMAGE_NAME" "${IMAGE_NAME}:${TAG}"
deploy:
  provider: script
  script: docker push "${IMAGE_NAME}"
  on:
    all_branches: true
